# Generated by Django 5.2 on 2025-06-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='menus',
        ),
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande'),
        ),
    ]
