# Generated by Django 5.2 on 2025-06-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_remove_commande_menus_alter_commande_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête à retirer'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
