# Generated by Django 5.2 on 2025-06-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
