# Generated by Django 5.2 on 2025-06-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_commande_montant_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
