# Generated by Django 5.2.3 on 2025-06-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='fas fa-bell', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('commande', 'Commande'), ('systeme', 'Système'), ('promo', 'Promotion')], default='systeme', max_length=20),
        ),
    ]
